version: '3.6'

services:

  postgres:
    image: postgres:14-alpine
    container_name: kpp-postgres
    restart: "no"
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5439:5432
    networks:
      - dit-network
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB' ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local

networks:
  dit-network:
    driver: bridge
