apiVersion: v1
kind: Service
metadata:
  name: {{ include "users.fullname" . }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}00
      protocol: TCP
      name: http
  selector:
    {{- include "users.selectorLabels" . | nindent 4 }}
