config:
  db:
    url: ${DB_URL}
    schema: ${DB_SCHEMA}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
spring:
  jpa:
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      reply-timeout: ${RABBITMQ_TEMPLATE_REPLY_TIMEOUT:10000}
